tap "felixkratz/formulae"
tap "hqhq1025/clipaste"
tap "nikitabobko/tap"

# Portable shell and development tools.
brew "bash"
brew "bat"
brew "coreutils"
brew "eza"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "go"
brew "httpie"
brew "jq"
brew "node"
brew "nvm"
brew "prettier"
brew "python"
brew "pyenv"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "yarn"
brew "z"
brew "zsh-autosuggestions"
brew "zsh-vi-mode"
brew "bat-extras"

# Clipboard and opt-in window-management services.
brew "hqhq1025/clipaste/clipaste"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"

# Base applications used on both work and personal projects.
cask "1password"
cask "1password-cli"
cask "chatgpt"
cask "codex"
cask "nikitabobko/tap/aerospace"
cask "font-hack-nerd-font"
cask "ghostty"
cask "raycast"
cask "shottr"
cask "docker-desktop"
